### ISSUE TITLE
您的网络好像缺失很多重要的包，比如test_util_1.py还有dataloader等

### ISSUE THREAD

**Issue by smallkaka** [SUST-reynole/ASE-Net#1]
您的网络好像缺失很多重要的包，比如test_util_1.py还有dataloader等

**Comment by HengfanLi** [comment]
> 您的网络好像缺失很多重要的包，比如test_util_1.py还有dataloader等

他意思是，让你去那个UA-MT那边，自己搞那些少的包补上去就好啦。

**Comment by smallkaka** [comment]
谢谢你，我有这样做，但是后面运行过程中还是出现了一些问题。

**Comment by HengfanLi** [comment]
> 
我跑完了，但是发现根本出不了结果，全是0，0，0奇了怪了，不知道怎么回事，你能加我QQ交流一下吗。1401210020

**Comment by HengfanLi** [comment]
> 谢谢你，我有这样做，但是后面运行过程中还是出现了一些问题。

我跑完了，但是发现根本出不了结果，全是0，0，0奇了怪了，不知道怎么回事，你能加我QQ交流一下吗。1401210020

**Comment by smallkaka** [comment]
搞的时间有点长，我发现我的网络是可以正确跑完的，我加你了

**Comment by smallkaka** [comment]
搞的时间有点长，我发现我的网络是可以正确跑完的，我加你了

**Comment by thundercult** [comment]
> 搞的时间有点长，我发现我的网络是可以正确跑完的，我加你了
你好，我也遇到了几个小问题，可以加你请教一下吗

**Comment by HengfanLi** [comment]
> > 搞的时间有点长，我发现我的网络是可以正确跑完的，我加你了
> > 你好，我也遇到了几个小问题，可以加你请教一下吗

QQ1401210020

**Comment by SUST-reynole** [comment]
请联系第一作者杜小刚老师，谢谢




--
发自我的网易邮箱手机智能版



在 2023-01-10 16:40:59，HengfanLi ***@***.***> 写道：


搞的时间有点长，我发现我的网络是可以正确跑完的，我加你了
你好，我也遇到了几个小问题，可以加你请教一下吗

QQ1401210020

**Comment by Pitrickstar** [comment]
> 搞的时间有点长，我发现我的网络是可以正确跑完的，我加你了

您好  想问一下lib里面没有那个transforms的包这个问题是怎么解决的呀

**Comment by Gardeniia** [comment]
> > 搞的时间有点长，我发现我的网络是可以正确跑完的，我加你了
> 
> 您好 想问一下lib里面没有那个transforms的包这个问题是怎么解决的呀

您好，请问你解决这个问题了吗

**Comment by feililucky** [comment]
Hello, how did you solve this problem,from lib import transforms_for_noise，
 thank you very much for your help!

**Comment by adaffas** [comment]
您好，我发现您的网络好像缺失test_util_1.py和dataloader包
